# Generated by Django 4.1.4 on 2022-12-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="category",
        ),
        migrations.AddField(
            model_name="books",
            name="category",
            field=models.ManyToManyField(to="books.category"),
        ),
    ]
